# Site settings
title: Markdown CV Template
email: jeff.w.hollister@gmail.com
description: CV Template
baseurl: "/cv_md" # the subpath of your site, e.g. /blog/
url: "http://jwhollister.com"
twitter_username: jhollist
github_username:  jhollist

# Build settings
markdown: kramdown
